version: 0.2
env:
  variables:
    REPOSITORY_URI: "056588440767.dkr.ecr.us-east-2.amazonaws.com/text-sum-server"
    key: "value"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - Download model...
      - mkdir -p server/model/data/saved_models
      - aws s3 cp s3://text-sum-nlp-mlops-bucket/model/0003699.tar server/model/data/saved_models/0003699.tar
  build:
    commands:
      - echo Build started on `date`
      - printf '{"consumer_key":"%s","consumer_secret":"%s","access_token":"%s","access_token_secret":"%s"}' $TWITTER_CONSUMER_KEY $TWITTER_CONSUMER_SECRET $TWITTER_ACCESS_TOKEN $TWITTER_ACCESS_TOKEN_SECRET > server/secrets/twitter_keys.json
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"text-sum-model-endpoint","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json